### ISSUE TITLE
pynetbox is out of date in requirements.txt

### ISSUE THREAD

**Issue by rlaroy** [netbox-community/Device-Type-Library-Import#48]
When trying to install requirements with pip install -r requirements.txt I get the following error: ERROR: Could not find a version that satisfies the requirement pynetbox==4.2.5 (from versions: 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.1.0, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.2.0, 3.3.0, 3.3.1, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.4.8, 3.4.9, 3.4.10, 3.4.11, 4.0.0rc1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 4.2.2, 4.2.4, 4.2.5, 4.3.0, 4.3.1, 4.3.3, 5.0.1, 5.0.3, 5.0.4, 5.0.5, 5.0.7, 5.0.8, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.2.1, 5.3.0, 5.3.1, 6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.2.0, 6.3.0, 6.4.0, 6.4.1, 6.5.0, 6.6.0, 6.6.1, 6.6.2)
ERROR: No matching distribution found for pynetbox==4.2.5

I updated pynetbox to use 6.6.2 and it worked without issue. Running RHEL 8.6 and Python 3.6.8

**Comment by minitriga** [comment]
Is this still a valid issue?

**Comment by oit-operations** [comment]
It looks like it, I just tried again and got the same error

**Comment by rlaroy** [comment]
It looks like it, I just tried again on a similar system and got the same error

**Comment by dmcken** [comment]
I would like the upgrade done as well since it makes the status netbox API which is not usable in 4.2.5

**Comment by danner26** [comment]
Hello all, the NetBox Community will be taking over this repository. Due to the fact that this issue has been around for a very long time and we have updated the requirements within this repository as well as the new codebase for NetBox and DeviceType-Library, I am going to close it. Should you encounter any further issues, please feel free to contact us. Thank you!
